// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3Oa1FOvha6m4liQnUQ9JCM5wrv0Id3I',
    appId: '1:914967389919:web:9e92f3db2caa8e8f27ab6a',
    messagingSenderId: '914967389919',
    projectId: 'congniguard',
    authDomain: 'congniguard.firebaseapp.com',
    storageBucket: 'congniguard.appspot.com',
    measurementId: 'G-63WK68WFKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39qydMSdp8tcc12cSqKT8a7zx5ThM7gk',
    appId: '1:914967389919:android:b1347dda6bc5ec4827ab6a',
    messagingSenderId: '914967389919',
    projectId: 'congniguard',
    storageBucket: 'congniguard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LtKJp-Aul1xok3ozXGR2ZPBdFihM22s',
    appId: '1:914967389919:ios:4d2f8584f033eef927ab6a',
    messagingSenderId: '914967389919',
    projectId: 'congniguard',
    storageBucket: 'congniguard.appspot.com',
    iosBundleId: 'com.example.congniguardAdmain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LtKJp-Aul1xok3ozXGR2ZPBdFihM22s',
    appId: '1:914967389919:ios:d94a04b32162925a27ab6a',
    messagingSenderId: '914967389919',
    projectId: 'congniguard',
    storageBucket: 'congniguard.appspot.com',
    iosBundleId: 'com.example.congniguardAdmain.RunnerTests',
  );
}
